### ISSUE TITLE
Podfile.lock out of sync

### ISSUE THREAD

**Issue by Siemian** [Mapwize/mapwize-ui-ios#10]
### Problem
`CocoaPods could not find compatible versions for pod "MapwizeSDK":`
### Description
After downloading master branch from the repository and trying to run `pod install` following error will occur:
```
pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "MapwizeSDK":
  In snapshot (Podfile.lock):
    MapwizeSDK (= 3.0.1)

  In Podfile:
    MapwizeSDK

    MapwizeUI (from `.`) was resolved to 2.0.4, which depends on
      MapwizeSDK (= 3.0.11)


You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `MapwizeSDK` inside your development pod `MapwizeUI`.
   You should run `pod update MapwizeSDK` to apply changes you've made.
```
### Solution
Update `Podfile.lock` file to point to MapwizeSDK 3.0.11

**Comment by emerciercontexeo** [comment]
Thanks for reporting.

A pod update was enough to avoid this error. 

However, I made the pod update on my side and push update podfile.lock

Etienne
