### ISSUE TITLE
Readme missing key info

### ISSUE THREAD

**Issue by Siemian** [Mapwize/mapwize-ui-ios#11]
### Problem
Following Initialization section from the read me file: https://github.com/Mapwize/mapwize-ui-ios#initialization does not allow us to have working Mapwize implementation.
After following all steps and running the app, this will be presented:
![Simulator Screen Shot - iPhone 8 - 2019-12-17 at 13 37 57](https://user-images.githubusercontent.com/1449108/70996141-77010d00-20d2-11ea-92c8-4f8266376aef.png)
This log will be available in the console:
```
MapwizeUIAppSwift[46521:13300249] Error retrieving venue Error Domain=MapwizeRemoteApi Code=401 "(null)"
```
### Description
To make it work we need to add `MWZApiKey` to the plist file. As this is not mentioned in the initialization section and logged error does not indicate clearly where is the problem, it can take some to discover what is wrong and how to fix it.
### Solution
Add info in the initialization section that adding api key in plist file is required.

**Comment by emerciercontexeo** [comment]
Thanks for reporting.

I just commit an updated readme with the required information.

Etienne
