### ISSUE TITLE
objectForKeyedSubscript

### ISSUE THREAD

**Issue by pranavpari** [Mapwize/mapwize-ui-ios#13]
Hello getting following crash with new update

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString objectForKeyedSubscript:]: unrecognized selector sent to instance 0x600002a0c3f0'

**Comment by emerciercontexeo** [comment]
Hello @pranavpari ,

Can you give me more context about this issue?

It is a bit hard for me to find something base on this report.

Etienne

**Comment by emerciercontexeo** [comment]
Fixed in 2.1.6
