### ISSUE TITLE
MapwizeUI build warnings - Xcode 10.2

### ISSUE THREAD

**Issue by Siemian** [Mapwize/mapwize-ui-ios#7]
`MapwizeForMapbox` which is a `MapwizeUI` dependency is generating build warnings in new version of Xcode. 
If `MapwizeUI` is integrated using Cocoapods and `Treat warnings as errors` is set to true in the project, those warnings break the build.
Here are build errors:
![Zrzut ekranu 2019-05-20 o 10 58 20](https://user-images.githubusercontent.com/1449108/58009474-d83a1100-7aee-11e9-8c2f-12fe9e37bdae.png)
Workaround for that issue is to set `Treat warnings as errors` to false. But that's not a good practice and developers should be able to use this flag as they want.

**Comment by Siemian** [comment]
@emerciercontexeo any update on fixing this?

**Comment by emerciercontexeo** [comment]
Hi @Siemian ,

Sorry about that, I missed this issue. I will take a look as soon as possible and fix warning on our side.

Etienne

**Comment by Siemian** [comment]
Thanks for the info, looking forward for the fix :)

**Comment by emerciercontexeo** [comment]
@Siemian I will do it in the next version of the SDK because there is a lot of Nullability issue to fix.

This should be in production at the end of the month.

**Comment by Siemian** [comment]
I understand, thank you

**Comment by emerciercontexeo** [comment]
@Siemian,

I tried to use the Treat Warnings as Errors on my side and I can't reproduce with the last version of MapwizeUI.

Do you still have this issue on your side?

Etienne

**Comment by Siemian** [comment]
It's fixed now, thanks.
Closing issue.
