### ISSUE TITLE
Style Place on client side

### ISSUE THREAD

**Issue by KenrickV-Hexaware** [Mapwize/mapwize-ui-ios#8]
I would like to indicate a place with a different color before or once the map loads. How can this be done?

I have tried the following in mapwizeViewDidLoad

MWZApi.getPlacesWithName("Meeting Room ABC", venue: mapwizeView.mapwizePlugin.getVenue(), success: {(place) in
                
              
                    let placeStyle = MWZStyle()
                    placeStyle.fillColor = "#000000"
                    placeStyle.strokeColor = "#FF0000"
                    placeStyle.strokeOpacity = 2
                    placeStyle.strokeWidth = 1
                    placeStyle.fillOpacity = 1
                    placeStyle.isShapeDisplay = true
                    placeStyle.isMarkerDisplay = true
                    
                mapwizeView.mapwizePlugin.setStyle(placeStyle, for: place)
                
            
        }, failure: {err in
            print("ERROR FETCHING PLACE")
            print(err)
        })
        
I am using swift.

**Comment by emerciercontexeo** [comment]
Hi,

For the moment, you can't set the style of a place before you enter the venue where the place belongs.

It will change in the near future.

I will keep this issue open in order to inform you when this update will be released.

Etienne

**Comment by KenrickV-Hexaware** [comment]
That's odd! The documentation clearly states "You can overwrite the style of any place at any time using the setStyle function."

Without this feature using Mapwize is rather pointless..any idea when the update will be released?

**Comment by emerciercontexeo** [comment]
Hi @KenrickV-Hexaware,

The last update of MapwizeSDK allows you to set the style before entering in a venue. The style will be applied when the places are displayed

Etienne
